# Remote Embedded Diana service setup w Resin.io
# Merck, Summer 2018

# resin docker-compose is 2.1 max
version: '2.1'

services:

#  broker:
#    image: redis
#    command: redis-server --requirepass passw0rd!
#    ports:
#      - "6379:6379"
#    environment:
#      TZ: America/New_York

  dicom:
    # Suggested to use orthanc 1.3.2 until a peer send bug is fixed
    # https://bitbucket.org/sjodogne/orthanc/issues/97/intermittent-peer-to-peer-send-failures-w
    image: derekmerck/orthanc:arm32v7
    ports:
      - "4242:4242"
      - "8042:8042"
    privileged: true
    environment:
      # If using Resin, turn on the init system, otherwise don't, it's breaking
      INITSYSTEM: "on"

  keras-tf:
    image: derekmerck/keras-tf
    links:
#      - broker
      - dicom
    privileged: true
    environment:
      INITSYSTEM: "on"
#      DIANA_BROKER: redis://:passw0rd!@broker:6379/1
#      DIANA_RESULT: redis://:passw0rd!@broker:6379/2
#    depends_on:
#      - broker
